version: '3.4'

services: 
    db:
        image: ${DBMS}:${DBMS_VERSION}
        environment: 
            # Change these lines to your specific needs
            # Don't forget to edit the .env file to customize your values
            - MYSQL_ROOT_PASSWORD=${DBMS_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes: 
            - type: volume
              source: db-data
              target: ${DBMS_TARGET_VOLUME}
        ports: 
            - 3307:3306

    php:
        depends_on: 
            - db
        build:
            context: .
            dockerfile: ./dockerfiles/php/Dockerfile
            args:
                - version=${PHP_VERSION}
                - os=${PHP_OS}
                - docker_php_ext=${PHP_DB_EXT} ${PHP_MANDATORY_EXT} ${PHP_IMAGE_EXT}
                - classic_php_ext= ${CLASSIC_PHP_EXTENSION}
                - package_manager=${OS_PACKAGE_MANAGER}
                - extension_package=${PHP_VERSION}
        volumes: 
            - ./ez-platform:/var/www/ez-platform:rw
            - ./architecture/install-files/parameters.yml:/var/www/ez-platform/app/config/parameters.yml
            - ./architecture/install-files/auth.json:/var/www/ez-platform/auth.json
    
    # server:

volumes: 
    db-data: {}